'use client';

import React from 'react';
import { NodeOrigin } from '@/types/curriculum';

const ORIGIN_CONFIG: Record<NodeOrigin, { label: string; className: string } | null> = {
  manual: null, // Don't show badge for manual items
  source: { label: 'FROM PDF', className: 'bg-emerald-50 text-emerald-600 border-emerald-200' },
  inferred: { label: 'AI INFERRED', className: 'bg-amber-50 text-amber-600 border-amber-200' },
  edited: { label: 'EDITED', className: 'bg-blue-50 text-blue-600 border-blue-200' },
};

interface OriginBadgeProps {
  origin: NodeOrigin;
}

export function OriginBadge({ origin }: OriginBadgeProps) {
  const config = ORIGIN_CONFIG[origin];
  if (!config) return null;

  return (
    <span
      className={`text-[10px] px-1.5 py-0.5 rounded border font-medium tracking-wide ${config.className}`}
      title={
        origin === 'source'
          ? 'Extracted directly from the uploaded document'
          : origin === 'inferred'
          ? 'Generated by AI based on document context'
          : 'Modified after generation'
      }
    >
      {config.label}
    </span>
  );
}
